# Generated by Django 3.2.7 on 2021-10-01 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_of_problem', models.TextField()),
                ('answer', models.TextField(default='В рассмотрении', max_length=256)),
                ('status', models.CharField(choices=[('Нерешен', 'Нерешен'), ('Решен', 'Решен'), ('Замарожен', 'Замарожен')], default='Нерешен', max_length=120)),
            ],
        ),
    ]
